BREAKING: ConnError::Failed now contains RetryError<FailedAttemptError>)
